DEFAULT_ROLE = "DISPATCHER"

ROLE_ADMIN = "ADMIN"
ROLE_FLEET_MANAGER = "FLEET_MANAGER"
ROLE_DISPATCHER = "DISPATCHER"
ROLE_SAFETY_OFFICER = "SAFETY_OFFICER"
ROLE_FINANCIAL_ANALYST = "FINANCIAL_ANALYST"

TOKEN_TYPE = "bearer"
