"""add_notifications_and_vehicle_documents_fields

Revision ID: b6bc86f9c2b7
Revises: f909d1939d4d
Create Date: 2026-07-12 15:25:02.211660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bc86f9c2b7'
down_revision: Union[str, Sequence[str], None] = 'f909d1939d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alter enum to support new document types
    op.execute("ALTER TYPE document_type_enum ADD VALUE IF NOT EXISTS 'RC'")
    op.execute("ALTER TYPE document_type_enum ADD VALUE IF NOT EXISTS 'FITNESS'")
    op.execute("ALTER TYPE document_type_enum ADD VALUE IF NOT EXISTS 'PERMIT'")
    op.execute("ALTER TYPE document_type_enum ADD VALUE IF NOT EXISTS 'ROAD_TAX'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('LICENSE_EXPIRY', 'VEHICLE_DOCUMENT_EXPIRY', 'MAINTENANCE_DUE', 'MAINTENANCE_OVERDUE', 'GENERAL', name='notification_type_enum'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('maintenance_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_driver_id'), 'notifications', ['driver_id'], unique=False)
    op.create_index(op.f('ix_notifications_maintenance_id'), 'notifications', ['maintenance_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_vehicle_id'), 'notifications', ['vehicle_id'], unique=False)
    op.add_column('vehicle_documents', sa.Column('document_number', sa.String(length=100), nullable=True))
    op.add_column('vehicle_documents', sa.Column('file_name', sa.String(length=255), nullable=True))
    op.add_column('vehicle_documents', sa.Column('issue_date', sa.Date(), nullable=True))
    op.add_column('vehicle_documents', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.add_column('vehicle_documents', sa.Column('remarks', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'vehicle_documents', 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicle_documents', type_='foreignkey')
    op.drop_column('vehicle_documents', 'remarks')
    op.drop_column('vehicle_documents', 'uploaded_by')
    op.drop_column('vehicle_documents', 'issue_date')
    op.drop_column('vehicle_documents', 'file_name')
    op.drop_column('vehicle_documents', 'document_number')
    op.drop_index(op.f('ix_notifications_vehicle_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_maintenance_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_driver_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
