"""add_is_active_and_odometers

Revision ID: bad3ecef7f09
Revises: eca3294b5c18
Create Date: 2026-07-12 13:36:25.902030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad3ecef7f09'
down_revision: Union[str, Sequence[str], None] = 'eca3294b5c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('trips', sa.Column('start_odometer', sa.Numeric(precision=10, scale=2), nullable=False, server_default=sa.text('0.0')))
    op.add_column('trips', sa.Column('end_odometer', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'end_odometer')
    op.drop_column('trips', 'start_odometer')
    op.drop_column('drivers', 'is_active')
    # ### end Alembic commands ###
